Repository jiyoon1156/mrcamel-assignment2, pull requests merged in 2021-07, with the labels that each got.

#9 [FEAT] 기본 리액트 라우터 세팅
  package-lock.json
  package.json
  src/App.js
Labels: feature

#11 [STYLE] CSS 리셋
  src/styles/.gitkeep
  src/styles/GlobalStyles.js
Labels: style

#12 [FEAT] 상품 조회이력 목록 페이지 초기세팅
  src/App.js
  src/pages/RecentList.js
  src/pages/RecentList/FilterBar/Filter/BrandFilter.js
  src/pages/RecentList/FilterBar/Filter/NotInterestFilter.js
  src/pages/RecentList/FilterBar/Filter/SortingFilter.js
  src/pages/RecentList/FilterBar/FilterBar.js
  src/pages/RecentList/ProductList/ProductList.js
  src/pages/RecentList/RecentList.js
Labels: feature

#13 gnb 추가
  .eslintrc.json
  src/App.js
  src/components/Button.js
  src/components/GlobalNavbar.js
Labels: feature

#15 [FEAT] Main 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/components/ProductList.js
  src/pages/Main.js
  src/styles/Theme.js
Labels: feature

#17 [FEAT] Storage 를 set, get, remove 할 수 있는 util 생성
  src/utils/.gitkeep
  src/utils/Storage.js
Labels: feature

#19 Product 페이지 ver.1 완성
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/components/ProductList.js
  src/pages/Main/Main.js
  src/pages/Product.js
  src/pages/Product/Product.js
Labels: feature

#20 [FEAT] 관심없는 상품 숨기기 기능 구현
  src/pages/RecentList/FilterBar/Filter/NotInterestFilter.js
  src/pages/RecentList/FilterBar/FilterBar.js
  src/pages/RecentList/ProductList/ProductList.js
  src/pages/RecentList/RecentList.js
Labels: feature

#22 [FEAT] Product 클릭 시 로컬스토리지에 상품조회이력(인덱스) 추가 기능 제작
  src/pages/Product/Product.js
Labels: feature

#24 [FEAT] 정렬 필터 구현
  src/pages/RecentList/FilterBar/Filter/SortingFilter.js
  src/pages/RecentList/FilterBar/FilterBar.js
  src/pages/RecentList/ProductList/ProductList.js
  src/pages/RecentList/RecentList.js
Labels: feature

#30 [STYLE] 조회 이력 페이지 디자인 #25
  src/pages/RecentList/FilterBar/Filter/NotInterestFilter.js
  src/pages/RecentList/FilterBar/Filter/SortingFilter.js
  src/pages/RecentList/FilterBar/FilterBar.js
  src/pages/RecentList/RecentList.js
Labels: feature, refactor

#31 [FIX & FEAT] 로컬스토리지 lastSaveDate & 상품 조회 이력 문제점 fix
  src/pages/Product/Product.js
Labels: bug, feature

#32 [FEAT] ProductList 관심없음 상품 링크 접근 못하게 추가
  src/components/ProductList.js
  src/constants/.gitkeep
  src/constants/Constants.js
  src/utils/Storage.js
Labels: feature

#34 [REFACTOR] 조회 이력 페이지 ProductList 컴포넌트 변경 #33
  src/components/ProductList.js
  src/pages/RecentList/RecentList.js
Labels: refactor

#35 [FEAT] 자정 Storage reset
  src/pages/Main/Main.js
Labels: feature

#36 [FEAT] 브랜드별 필터 구현
  .eslintrc.json
  package-lock.json
  public/index.html
  src/pages/RecentList/FilterBar/Filter/BrandFilter.js
  src/pages/RecentList/FilterBar/FilterBar.js
  src/pages/RecentList/ProductList/ProductList.js
  src/pages/RecentList/RecentList.js
Labels: feature

#37 [FIX] 변경사항 추가
  src/components/ProductList.js
  src/pages/RecentList/ProductList/ProductList.js
  src/pages/RecentList/RecentList.js
Labels: refactor

#40 [FIX] Product page : 옵셔널 체이닝 사용으로인한 undefined 출력 버그 해결
  src/pages/Product/Product.js
Labels: bug

#41 [FEAT] Product page : 랜덤 조회 시 로딩 효과 추가
  src/App.js
  src/components/Spinner.js
  src/pages/Product/Product.js
Labels: feature

#42 [STYLE] 조회 이력 페이지 FilterBar 디자인 수정
  src/pages/RecentList/FilterBar/Filter/BrandFilter.js
  src/pages/RecentList/FilterBar/Filter/NotInterestFilter.js
  src/pages/RecentList/FilterBar/Filter/SortingFilter.js
  src/pages/RecentList/FilterBar/FilterBar.js
  src/pages/RecentList/RecentList.js
Labels: style

#43 [FEAT] 로컬스토리지 초기화 코드(날짜 베이스) 제작
  src/App.js
Labels: feature
